always_on_top = true
auto_start_break_timer = true
auto_start_on_app_startup = false
auto_start_work_timer = true
default_focus_label = "Focus"
default_long_break_label = "Long break"
default_short_break_label = "Short break"
desktop_notifications = true
focus_duration = 1500
long_break_duration = 1200
max_round_number = 4
max_session_duration = 5400
minimize_to_tray = true
minimize_to_tray_on_close = true
muted = false
short_break_duration = 300
start_minimized = false
system_startup_auto_start = false
theme = "catppuccin mocha"
tick_sounds_during_work = true
tick_sounds_during_break = true
